CREATE TABLE USER_DATA (
    USER_ID INT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR2(255) NOT NULL,    
	LAST_NAME VARCHAR2(255) NOT NULL,    
    AGE INT NOT NULL,
	COUNTRY VARCHAR2(100)
);

CREATE SEQUENCE USER_SEQ
START WITH 101
INCREMENT BY 1
MAXVALUE 999999
CYCLE;

CREATE TABLE VEHICLE_DATA (
	VEHICLE_ID INT NOT NULL PRIMARY KEY,
	VEHICLE_TYPE VARCHAR2(50) NOT NULL,
	VEHICLE_NUMBER VARCHAR2(50) NOT NULL,
	MANUFACTURE_YEAR INT NOT NULL,
	USER_ID INT
);

ALTER TABLE VEHICLE_DATA ADD FOREIGN KEY (USER_ID) REFERENCES USER_DATA(USER_ID);

CREATE SEQUENCE VEHICLE_SEQ
START WITH 101
INCREMENT BY 1
MAXVALUE 999999
CYCLE;

CREATE TABLE VEHICLE_MAINTAINANCE_DATA (
	VEH_MAINTAINANCE_ID INT NOT NULL PRIMARY KEY,
	MAINTAINANCE_COST INT NOT NULL,
	MAINTAINANCE_DATE DATE,
	COMMENTS VARCHAR2(255),
	VEHICLE_ID INT
);

ALTER TABLE VEHICLE_MAINTAINANCE_DATA ADD FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE_DATA(VEHICLE_ID);

CREATE SEQUENCE VEH_MAINTAINANCE_SEQ
START WITH 101
INCREMENT BY 1
MAXVALUE 999999
CYCLE;